### ISSUE TITLE
tabset does not end correctly

### ISSUE THREAD

**Issue by chenlinear** [yihui/misc.js#1]
Hi yihui, thanks for the good work! `tabsets.js` is really convenient to use and I like how lightweight it is. I run into a bug and I am wondering if you can help me with it.

It is with [my blog](https://github.com/ChenLi2049/ChenLi2049.github.io) based on Hugo 0.111.1. The tabset does not end with `<!-- tabset:my-tabs -->`. Here's how to reproduce it.

1. Create a file `".\themes\maverick\layouts\partials\helpers\tabsets.html"` with the following content:

```html
<script src="https://cdn.jsdelivr.net/npm/@xiee/utils/js/tabsets.min.js" defer></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils/css/tabsets.min.css">
```

2. Add this line as line 90 in `".\themes\maverick\layouts\partials\head.html"`.

```html
{{ if .Params.tabsets }}{{ partial "helpers/tabsets.html" . }}{{ end }}
```

3. Create a file `".content/posts/20231012-title-of-the-post.md"` with the following content:

````Markdown
---
author: "Chen Li"
title: "Title of the Post"
date: "2023-10-12"
tags: 
- SomeTag
math: true
tabsets: true
---

some content.

## Demo tabs {.tabset}

### First tab {.active}

Some tab content.

### Second tab

| x   | y   | z   |
|-----|-----|-----|
| 1   |     |     |
| 2   |     |     |
| 3   |     |     |


### Third tab

```python
import numpy as np
```

### Fourth tab

$\LaTeX$

<!-- tabset:my-tabs -->

The previous tabset is supposed to be ended before this comment.
````

4. The previous tabset does not end before the comment `<!-- tabset:my-tabs -->`. It ends correctly with `## `, but sometimes I want to write something else after the tabset.

Also, is there a way not to show the titles of tabsets in the table of content at the beginning of posts? I just feel like tabsets and `\subsection{}` (borrowing the concept from LaTeX) are not of the same rank. I saw tabsets in [d2l](https://d2l.ai/chapter_linear-regression/linear-regression.html) and I really like the idea of tabsets.

Thanks!

**Comment by yihui** [comment]
The HTML comment must contain the ID of the starting element. Please see Step 3 in the doc: https://yihui.org/en/2023/10/section-tabsets/#markdown-users If you use `<!-- tabset:my-tabs -->`, your starting element must have the ID `my-tabs`.

> is there a way not to show the titles of tabsets in the table of content at the beginning of posts?

That'll require more work. Let me think about it.

**Comment by chenlinear** [comment]
Thanks! I changed two lines and it works.

```markdown
## Demo tabs {.tabset #demo-tabs}

...

<!-- tabset:demo-tabs-->
```

As for table of content, I have an idea that maybe don't start with `## ` and `### `?

**Comment by yihui** [comment]
You can create tabsets from bullet lists now, which can avoid the TOC problem. Please read the doc again: https://yihui.org/en/2023/10/section-tabsets/#markdown-users

Note that your browser may load a cached version of the script `https://cdn.jsdelivr.net/npm/@xiee/utils/js/tabsets.min.js`, and you need to force refresh the page (`Cmd + Shift + R` on macOS and `Ctrl + F5` on other platforms). Or force using the version 1.6.3: `https://cdn.jsdelivr.net/npm/@xiee/utils@1.6.3/js/tabsets.min.js`

**Comment by chenlinear** [comment]
Thanks, TOC problem can be avoided using bullet lists, you may close this issue. Also, 4 space indentation works; pictures fit into the tabsets too, here's my final markdown file as an example (`$\LaTeX$` is a display error with GitHub):

```markdown
---
author: "Chen Li"
title: "Title of the Post"
date: "2023-10-12"
tags: 
- SomeTag
math: true
tabsets: true
---

some content.

<div class="tabset"></div>

- First tab <!--active-->

    Some tab content.

- Second tab

    | x   | y   | z   |
    |-----|-----|-----|
    | 1   |     |     |
    | 2   |     |     |
    | 3   |     |     |

- Third tab

    ```python
    import numpy as np
    ```

- Fourth tab

    $\LaTeX$

- Fifth tab

    ![](link_to_a_picture.jpg)

The previous tabset will be ended before this comment.
```
