### ISSUE TITLE
可以让宽度 1280px 的设备显示侧面脚注和目录吗？

### ISSUE THREAD

**Issue by CyrusYip** [yihui/misc.js#3]
我用的屏幕经过系统缩放后宽度都是 1280px（2560 × 1440	200% 缩放、1920 × 1080 150% 缩放），得加 1px 宽度才能看到侧面脚注和目录。

受影响的网站：

https://prose.yihui.org/about/

https://yihui.org/litedown/

**Comment by yihui** [comment]
可以。理论上断点应该设置在 1200（正文 800 + 侧栏 200 * 2），我忘记为什么用了 1280，可能是参考了 Bootstrap。我再看看。

**Comment by yihui** [comment]
断点改为了 1264px。

需要强制刷新浏览器清除缓存的 CSS 方能见效。

**Comment by CyrusYip** [comment]
> 需要强制刷新浏览器清除缓存的 CSS 方能见效。

正想反馈这个问题。我认为用带版本号的链接（<https://cdn.jsdelivr.net/npm/@xiee/utils@1.12.21/css/article.min.css>）比较好，这样可以避免这个问题。

或者每次改了文件就清除 jsDelivr 的缓存。

```
curl https://purge.jsdelivr.net/npm/@xiee/utils/css/article.min.css
```

**Comment by yihui** [comment]
两个办法我都会用。对于我觉得需要立刻更新的尚在开发中的资源，我会使用版本号，如 <https://github.com/yihui/litedown/blob/2e6b07e91f9ef87d7e8f95c6e927233f9d2c6057/R/site.R#L316>；对那些我觉得基本上已经稳定下来的资源，我会清除 jsdelivr 缓存，但用户依然需要强制刷新，不然就等大约一周之后缓存自动失效。
